### ISSUE TITLE
feature request: reload schema button

### ISSUE THREAD

**Issue by scheiblr** [subzerocloud/subzero-cli#30]
it would be nice to have a key which reloads the schema in case one is feeding the DB from outside (postgrest as well as openresty).
Additionally having that feature usable as own CLI command as well without the UI would be great.

Kind regards,

**Comment by ruslantalpa** [comment]
if you use the dashboard and you move to the screen of a particular container, you could use `t` to reload that container

**Comment by scheiblr** [comment]
Thanks. As I remember, there was a function in postgrest to only reload the schema instead of restarting the entire container. I was more thinking about that. Currently I'm using the t key.

**Comment by ruslantalpa** [comment]
you are thinking about sending the HUP signal to postgrest and yes that is possible.
I think the best way to manage your situation (when the db structure is external an you can not monitor the file changes) is to automate it using pg_listen.

This is a 2 step process:
1) identify the exact command that will "restart/refresh" the state of postgrest and openresty when they are running in docker context
2) install a db trigger that emits a NOTIFY event when the schema changes and have pg_listen execute the command from step 1 on that event.

more details here https://postgrest.org/en/v4.4/admin.html#schema-reloading

as to what is the exact command for containers ... sending a HUP event to postgrest/openresty is exactly what happens when you press `r` ... here it is https://github.com/subzerocloud/subzero-cli/blob/master/src/watch.js#L38-L39


and the way to send it is here https://github.com/subzerocloud/subzero-cli/blob/master/src/watch.js#L46

so a complete command line would be :) (assuming you installed the trigger explained in the postgrest docs)

`pg_listen <db-uri> ddl_command_end "docker kill -s HUP subzerostarterkit_postgrest_1 && docker kill -s HUP subzerostarterkit_openresty_1"`

(adjust `subzerostarterkit_postgrest_1` and `subzerostarterkit_openresty_1` as needed)

after this you do your work in the db and pgrst/openresty containers will always be up to date with the db

**Comment by scheiblr** [comment]
amazing, thanks a lot! this works just fine :+1:
