### ISSUE TITLE
resetDb only drop the database but the created role will not

### ISSUE THREAD

**Issue by deftsp** [subzerocloud/subzero-cli#50]
"Reset DB" only drop the database, but the roles will not be dropped.

 I drop the roles in `db/src/sample_data/reset.sql`. With a quick solution, execute "db/src/sample_data/reset.sql" by modifying the `resetDb` function.

Is there a better solution to it? Maybe we can add an environment variable to specify the reset file.

**Comment by ruslantalpa** [comment]
it depends.
there are 2 types of reset:
a) the entire database (schema and data), this is related to subzero-cli and is performed when a file changes.
in this case it's better to drop the role before creating it like here https://github.com/subzerocloud/subzero-starter-kit/blob/e04e39f17d0dc605772dbd50b5e08ecfc947e386/db/src/authorization/roles.sql#L15-L16 

b) reset the sample data (without touching the schema), this reset is used when running "tests". this type of reset is not "related" to subzero-cli but rather to the "structure" of the starter kits. 
in this case, the reset is done by this function https://github.com/subzerocloud/subzero-starter-kit/blob/e04e39f17d0dc605772dbd50b5e08ecfc947e386/tests/common.js#L38 and indeed it calls the reset.sql file. You are welcome to change either the sql file or the js file since this is not a part of code "managed" by subzero-cli but rather by you, and you adapt it to your needs. That being said, i do not see why you would need to drop/create roles between running different integration tests. Roles/schema should only be altered in (a)

**Comment by deftsp** [comment]
Thanks for your reply. My project needing to create new roles by admin in http request.  Those roles should be drop when reset type (a).  My situation is not general enough.  Anyway, I  add a `db/src/before_reset_db.sql`  before resetDb in my fork.
