### ISSUE TITLE
subzero-migrations add 

### ISSUE THREAD

**Issue by titanLuLi** [subzerocloud/subzero-cli#61]
Can the subzero-migrations command ignore space or tab?

**Comment by ruslantalpa** [comment]
What do you mean by that? Spaces where?

**Comment by titanLuLi** [comment]
After I built the migration script, I need to manually move around the code in order for those scripts to run in test env, then the next time I build the migration script, subzero does not recognize those codes. I checked the only differences are space and tab.

**Comment by ruslantalpa** [comment]
Still not sure i follow :)
Can you paste here some sample sql in both "versions", first the exact thing the cli generated (and breaks) then the "adjusted" version (that fixes the problem)

**Comment by ruslantalpa** [comment]
i am not sure about the view but it's possible that the function definition is diffed/compared as a simple string so if you move around the function definition and your editor changes tabs to spaces (or the other way) you will get the mentioned behavior.

the `create table` comes back probably because it depends on the function.

If you are using migra, this is mentioned here https://github.com/djrobstep/migra/issues/188

Not sure there is a good solution besides "don't change (you or the editor) the lines referring to the function body in the generated migration file". apgdiff might probably have the same behaviour
